export const FINDINGS_CLOSING_CONTENT = {
  p1: `In the preceding sections we have provided details on the results of our investigation. <strong>If our investigation has not resolved your dispute, here’s what you can do next:</strong>`,
  list1: [
    `<b>Add a 100 - word statement to your report.</b> What this means is that you have the right to send us a note of 100 words or less describing your situation or why you disagree with the results, and we will add this statement to your report. Anyone who views your report will see this statement. Please know that if you include any medical information in your statement, this means you’re giving TransUnion permission to include that information in any future credit report we issue on your behalf.`,
    `<b>Dispute directly with the company that reported the information to us.</b> If you want changes made to information found on your credit report you may dispute with the company that reported it using the contact information listed in Your Investigation Results.`,
    `<b>Provide to us any other information or documents about your dispute.</b> Please visit <a href="https://www.transunion.com/dispute" target="_blank">www.transunion.com/dispute</a> and let us know you are filing a repeat dispute. Be sure to include any other information or documentation you feel will help us resolve your dispute.`,
    `<b>File a complaint</b> about the company reporting the account or about TransUnion with the Consumer Financial Protection Bureau or with your State’s Attorney General’s office. If there has been a change to your credit report as a result of our investigation, or if you have added a statement to your report, you may ask TransUnion to send an updated credit report to those who have received your report within the last 2 years for employment purposes or within the last 6 months for any other purpose.`,
  ],
  p2: `A Note on Inquiries`,
  p3: `An inquiry is posted on your credit report to notify you that a company has requested your report. Companies can only request a credit report for a legitimate business reason (called permissible purpose). Examples of permissible purpose include: credit transactions, employment consideration, review or collection of an existing account or other legitimate business need, insurance underwriting, government licensing, rental application or court order. Inquiries stay on your credit report for up to two(2) years. Each company that requested your credit report will be listed in the section on inquires, along with their contact information. Please note, a company doesn't always need your authorization to view your credit report as long as they have a permissible purpose. If you think an inquiry was made without a permissible purpose, we strongly encourage you to reach out to the company who requested your credit report to find out whether they have opened an account in your name. The company can then investigate and if they determine that someone fraudulently applied for credit in your name, they can close that account and send us a letter requesting removal of the inquiry. If you have specific information that the inquiry was made fraudulently, you can also call the TransUnion Fraud Victim Assistance department at 800-680-7289.`,
};
