export const FINDINGS_CONTACT_INFO = {
  p1: `Should You Wish to Contact TransUnion`,
  span1: `Please have your TransUnion FILE NUMBER available. Your unique FILE NUMBER is`,
  span2: `and also located at the top of this page.`,
  p2: `Online:`,
  p3: `To dispute information contained in your credit report, please visit the Dispute Center <a href="www.transunion.com/disputeonline " target="_blank" class="text-indigo-800">Dispute Center</a> or go to <a href="www.transunion.com/disputeonline" target="_blank" class="text-indigo-800">www.transunion.com/disputeonline</a>`,
  p4: `For more information please visit our <a href="" target="_blank">Frequently Asked Questions</a> or go to <a href="http://transunion.com/consumerfaqs" target="_blank" class="text-indigo-800">http://transunion.com/consumerfaqs</a>`,
  p5: `Mail:`,
  p6: `TransUnion P. O. Box 2000`,
  p10: `Chester, PA 19016-2000`,
  p7: `By Phone:`,
  p8: `(800) 916-8800`,
  p9: `You may contact us between the hours of 8:00 AM – 11:00 PM ET, Monday through Friday, except major holidays.`,
  span3: `Want to review a full copy of your credit report? If your Brave Credit account is currently active, visit the`,
  link1: `Credit Report`,
  span4: `section of the app found on the navigation bar and refresh your report. Or visit <a href="https://www.transunion.com/fullreport" target="_blank" class="text-indigo-800">transunion.com/fullreport<a/> to request a free disclosure of your full credit report.`,
};
