import { IReferral } from '@shared/interfaces/referrals.interface';

export const REFERRAL_ACTIVE: IReferral = {
  id: 'abc',
  referralCode: 'code',
  referredByCode: undefined,
  referredById: undefined,
  referredByEmail: undefined,
  suspended: false,
  enrolled: true,
  eligible: 1,
  totalReferred: 1,
  totalEarned: 0,
  totalBonus: 0,
  totalAddOn: 0,
  campaignActive: 'test_campaign',
  campaignActiveReferred: 1,
  campaignActiveEarned: 5,
  campaignActivePaid: 0,
  campaignActiveAddOn: 0,
  campaignActiveBonus: 0,
  campaignPrior: '',
  campaignPriorReferred: 0,
  campaignPriorEarned: 0,
  campaignPriorPaid: 0,
  campaignPriorAddOn: 0,
  campaignPriorBonus: 0,
  nextPaymentDate: '',
  notified: false,
  createdOn: undefined,
  modifiedOn: undefined,
};
