/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:aca920e3-dd7b-4e2f-91f0-865d978c6f76",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_6RQqasoH3",
    "aws_user_pools_web_client_id": "3la1dgv1c2fq2etrhpbu1ij6mn",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://t7a6gsqngvcwvmzmtoaylg2u4y.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "braveapp7123270838f144d09004f496c2f9ef0f113453-qa",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
